apiVersion: batch/v1
kind: Job
metadata:
  name: experiment-job
  namespace: default
spec:
  template:
    spec:
      schedulerName: custom
      containers:
      - name: sleep
        image: alexnjh/sleep:0.0.1
      restartPolicy: Never
  backoffLimit: 4
